// Health Connect ExerciseSessionRecord.EXERCISE_TYPE_* constants, from developer.android.com.
const EXERCISE_TYPES: Record<number, string> = {
  0: 'other workout',
  2: 'badminton',
  4: 'baseball',
  5: 'basketball',
  8: 'biking',
  9: 'biking stationary',
  10: 'boot camp',
  11: 'boxing',
  13: 'calisthenics',
  14: 'cricket',
  16: 'dancing',
  25: 'elliptical',
  26: 'exercise class',
  27: 'fencing',
  28: 'football american',
  29: 'football australian',
  31: 'frisbee disc',
  32: 'golf',
  33: 'guided breathing',
  34: 'gymnastics',
  35: 'handball',
  36: 'high intensity interval training',
  37: 'hiking',
  38: 'ice hockey',
  39: 'ice skating',
  44: 'martial arts',
  46: 'paddling',
  47: 'paragliding',
  48: 'pilates',
  50: 'racquetball',
  51: 'rock climbing',
  52: 'roller hockey',
  53: 'rowing',
  54: 'rowing machine',
  55: 'rugby',
  56: 'running',
  57: 'running treadmill',
  58: 'sailing',
  59: 'scuba diving',
  60: 'skating',
  61: 'skiing',
  62: 'snowboarding',
  63: 'snowshoeing',
  64: 'soccer',
  65: 'softball',
  66: 'squash',
  68: 'stair climbing',
  69: 'stair climbing machine',
  70: 'strength training',
  71: 'stretching',
  72: 'surfing',
  73: 'swimming open water',
  74: 'swimming pool',
  75: 'table tennis',
  76: 'tennis',
  78: 'volleyball',
  79: 'walking',
  80: 'water polo',
  81: 'weightlifting',
  82: 'wheelchair',
  83: 'yoga',
};

export function exerciseName(type: string): string {
  if (!/^\d+$/.test(type)) return type;
  return EXERCISE_TYPES[Number(type)] ?? `exercise type ${type}`;
}
